DemoSlack/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers  => {
             :registrations => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"

  post "/get_started" =>"home#get_started", as: "get_started"
end

DemoSlack/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DemoSlack/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	validate :validate_password, :validate_name
  	
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    def validate_password
	    if ["password","123456", "abcdef"].include?(self.password) 
	      errors.add(:password, "is not valid!")
	    end
  	end

  	def validate_name
  		if self.full_name.blank?
  			errors.add(:Name, "can't be blank")
  		end	
  	end
end

DemoSlack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

DemoSlack/app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!, except: [:index,:get_started] 

	def index
		
	end

	def index_new
		
	end

	def get_started
		if params[:email].present?
			if !User.find_by(email: params[:email]).present? 
				redirect_to new_user_registration_path(:email => params[:email]) 
			else
				flash[:alert] = "Email already registerd!"
				redirect_to root_path
			end
		else 
			flash[:alert] = "Please enter an email address"
			redirect_to root_path	
		end		
	end
end

DemoSlack/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	include DeviseHelper

	def create
		sign_up_prms = sign_up_params.merge!({full_name: params[:user][:full_name],password_confirmation: params[:user][:password]})
		build_resource(sign_up_prms)
		resource.save
		yield resource if block_given?
		if resource.persisted?
			if resource.active_for_authentication?
				sign_in(resource_name, resource) 
				redirect_to root_path
			else
				set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
				expire_data_after_sign_in!
				respond_with resource, location: after_inactive_sign_up_path_for(resource)
			end
		else
			flash[:errors] = resource.errors.full_messages
			@email = params[:user][:email] if params[:user][:email].present?
			clean_up_passwords resource
			set_minimum_password_length
			respond_with resource
		end
	end

	
	def sign_up_params
		devise_parameter_sanitizer.sanitize(:sign_up)
	end

end

DemoSlack/app/helpers/application_helper.rb
module ApplicationHelper
end

DemoSlack/app/helpers/home_helper.rb
module HomeHelper
end

DemoSlack/app/views/home/index.html.erb
<!-- slack_imge.png -->
<style>
   .frmContainer h1{
       font-family: "Times New Roman",Georgia,serif;
        font-weight: 800;
        line-height: 1.05;
        letter-spacing: normal;
        font-size: 2.2rem;
        margin-bottom: 2rem;
        margin-top: 0;
        margin-left: 0;
        font-size: 80px;
    }

    .frmContainer p{
        color: #5b5e6d;
        margin-bottom: 2rem;
        font-size: 18px;
    }
    .frmContainer .input-group{display: inline-block;vertical-align: top;}
    .frmContainer .input-group-email input {
        background-color: #fff;
        color: #5b5e6d;
        text-decoration: none;
        font-family: Slack-Averta,appleLogo,sans-serif;
        font-weight: 400;
        line-height: 1.2;
        letter-spacing: normal;
        font-size: 1rem;
        border: 1px solid #a8a9b0;
        border-radius: 4px !important;
        box-shadow: none;
        padding: 1.15rem 1rem;
        display: block;
        margin-bottom: 0px !important;
        width: 100%;
    }
    .input-group-email{width: 60%;margin-right: 10px;}
    .input-group-button{width:calc(40% - 14px);}    
    .input-group-button button{
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border: none;
        cursor: pointer;
        border-radius: 4px;
        text-align: center;
        font-family: Slack-Averta,appleLogo,sans-serif;
        font-weight: 700;
        line-height: 1.3;
        letter-spacing: normal;
        font-size: .9rem;
        text-transform: uppercase;
        text-decoration: none;
        padding: 20px 40px 20px;
        display: block;
        width: 100%;
        transition: box-shadow 420ms cubic-bezier(.165,.84,.44,1),color 420ms cubic-bezier(.165,.84,.44,1),background 420ms cubic-bezier(.165,.84,.44,1);
    }
</style>
<% if !user_signed_in?%>
	<section style="padding: 30px 0px;">
	   <div class="container">
	        <div class="row">
	            <div class="col-md-5">
	                <img src="/assets/slack_imge.png" alt="" style="max-width: 100%" />
	            </div>
	            <div class="col-md-5 col-md-offset-2">
	                <div class="frmContainer">
	                    <h1>Where Work Happens</h1>
	                    <p>When your team needs to kick off a project, hire a new employee, deploy some code, review a sales contract, finalize next year's budget, measure an A/B test, plan your next office opening, and more, Slack has you covered.</p>
	                    <form class="" action="<%= get_started_path%>" method="post">
	                           <input name="utf8" type="hidden" value="" class="">
	                        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" class="">

	                          <!-- Email -->
	                        <div class="input-group" style="width: 60%">
	                            <input type="email" id="defaultLoginFormEmail" name="[email]" class="form-control mb-4" placeholder="Enter Your Email" required> <br>
	                          <!-- <span class="input-group-btn"> -->
	                            <!-- <button class="btn btn-default" type="button">Go!</button> -->
	                             <!-- </span> -->
	                          <!-- Sign in button -->
	                        </div>
	                        <div class="input-group">
	                            <button class="btn btn-info btn-block" type="submit">Get Started</button>
	                        </div>
	                          <!-- Register -->
	                          <!-- Social login -->
	                        
	                    </form>
	                </div>
	             </div>
	        </div>
	    </div>    
	</section>
<%else%>
<div class="col-md-4 col-md-offset-4">
	<h2>Welcome to home</h2><br>
	<a href="<%= destroy_user_session_path%>" data-method="delete"> Click to Logout </a>	
</div>	
<% end%>

DemoSlack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoSlack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>


<!-- Default form login -->

<!-- Default form login -->